[bar.default]
background_opacity = 0.019999999552965164
concave_edge_corners = false
margin_ends = 0
radius_top_left = 0
radius_top_right = 0
scale = 1.1500000096857548
shadow = false

[battery]
warning_threshold = 20

[brightness]
minimum_brightness = 0.0099999997764825821

[dock]
background_opacity = 0.0
icon_size = 37
pinned = [ "firefox", "org.kde.dolphin", "com.mitchellh.ghostty" ]
reserve_space = false
shadow = false
show_dots = true
smart_auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 420.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 360.0

[location]
auto_locate = true

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 768.0
    cy = 645.60003662109375
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true

[notification]
keep_dismissed_in_history = false

[shell]
niri_overview_type_to_launch_enabled = true
polkit_agent = true
screen_time_enabled = true

    [shell.launcher]
    categories = false

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Dracula"
mode = "dark"
source = "builtin"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "niri" ]
    community_ids = [ "libreoffice", "fastfetch" ]

[wallpaper]
directory = "/home/sanzay/Pictures/Wallpapers"
transition_on_startup = true

    [wallpaper.automation]
    interval_seconds = 180

    [wallpaper.default]
    path = "/home/sanzay/Pictures/Wallpapers/among-trees-campsite.jpg"

    [wallpaper.last]
    path = "/home/sanzay/Pictures/Wallpapers/among-trees-campsite.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/sanzay/Pictures/Wallpapers/among-trees-campsite.jpg"
