[files]
recent_files=/home/sanzay/.config/btop/btop.conf;/home/sanzay/.config/mimeapps.list;/home/sanzay/.config/starship.toml;/home/sanzay/.config/niri/cfg/keybinds.kdl;/home/sanzay/Downloads/arch-backup/.config/menus/applications-kmenuedit.menu;/home/sanzay/Downloads/arch-backup/masked-services.txt;/home/sanzay/Downloads/arch-backup/.config/user-dirs.locale;/home/sanzay/.bash_profile;/home/sanzay/.bash_logout;/home/sanzay/Downloads/arch-backup/enabled-services.txt;
recent_projects=
current_page=3
FILE_NAME_0=89;None;0;EUTF-8;1;1;0;%2Fhome%2Fsanzay%2F.config%2Fniri%2Fcfg%2Fkeybinds.kdl;0;4
FILE_NAME_1=0;TOML;0;EUTF-8;1;1;0;%2Fhome%2Fsanzay%2F.config%2Fstarship.toml;0;4
FILE_NAME_2=0;None;0;EUTF-8;1;1;0;%2Fhome%2Fsanzay%2F.config%2Fmimeapps.list;0;4
FILE_NAME_3=0;Conf;0;EUTF-8;1;1;0;%2Fhome%2Fsanzay%2F.config%2Fbtop%2Fbtop.conf;0;4

[project]
session_file=
project_file_path=/home/sanzay/projects

[geany]
treeview_position=0
msgwindow_position=694
geometry=26;23;744;761;0;
sidebar_page=0

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=-1
position_find_y=-1
position_replace_x=-1
position_replace_y=-1
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
